-- Seasonal Plex collections (Halloween first). The list lives here so it
-- can be edited from the Hub without an app update; plex-seasonal matches it
-- against the Plex server once and every box reads that shared answer from
-- seasonal_cache. Service role only (RLS on, no policies): the Hub edits it
-- through plex-seasonal, which checks has_role(admin).
create table if not exists public.seasonal_rows (
  season text not null,
  row_id text not null,
  title text not null,
  kids boolean not null default false,
  sort int not null default 0,
  primary key (season, row_id)
);
create table if not exists public.seasonal_titles (
  id uuid primary key default gen_random_uuid(),
  season text not null,
  row_id text not null,
  title text not null,
  year int,
  is_show boolean not null default false,
  sort int not null default 0,
  created_at timestamptz not null default now(),
  foreign key (season, row_id) references public.seasonal_rows (season, row_id) on delete cascade
);
create index if not exists seasonal_titles_row on public.seasonal_titles (season, row_id, sort);
create table if not exists public.seasonal_cache (
  season text primary key,
  machine_id text,
  rows jsonb not null default '[]'::jsonb,
  found jsonb not null default '{}'::jsonb,
  built_at timestamptz,
  building_at timestamptz,
  dirty boolean not null default true
);
alter table public.seasonal_rows enable row level security;
alter table public.seasonal_titles enable row level security;
alter table public.seasonal_cache enable row level security;

insert into public.seasonal_rows (season, row_id, title, kids, sort) values
  ('halloween', 'kids', '🎃 Kids & Family Halloween', true, 0),
  ('halloween', 'kidshows', 'Family Spooky Shows', true, 10),
  ('halloween', 'night', 'Halloween Night', false, 20),
  ('halloween', 'classics', 'Horror Classics', false, 30),
  ('halloween', 'occult', 'Occult, Demons & Possession', false, 40),
  ('halloween', 'witches', 'Witches & Witchcraft', false, 50),
  ('halloween', 'haunted', 'Haunted Houses & Ghosts', false, 60),
  ('halloween', 'slashers', 'Slashers', false, 70),
  ('halloween', 'gore', 'Gore & Extreme Horror', false, 80),
  ('halloween', 'monsters', 'Vampires, Werewolves & Monsters', false, 90),
  ('halloween', 'zombies', 'Zombies', false, 100),
  ('halloween', 'comedy', 'Horror Comedies', false, 110),
  ('halloween', 'found', 'Found Footage', false, 120),
  ('halloween', 'psych', 'Psychological Horror', false, 130),
  ('halloween', 'new', 'New Horror', false, 140),
  ('halloween', 'series', 'Spooky Series', false, 150)
on conflict (season, row_id) do nothing;

-- Seeded once: an edited list is not overwritten if this runs again.
insert into public.seasonal_titles (season, row_id, title, year, is_show, sort)
select * from (values
  ('halloween', 'kids', 'Hocus Pocus', 1993, false, 0),
  ('halloween', 'kids', 'Hocus Pocus 2', 2022, false, 10),
  ('halloween', 'kids', 'The Nightmare Before Christmas', 1993, false, 20),
  ('halloween', 'kids', 'Coraline', 2009, false, 30),
  ('halloween', 'kids', 'Monster House', 2006, false, 40),
  ('halloween', 'kids', 'ParaNorman', 2012, false, 50),
  ('halloween', 'kids', 'Frankenweenie', 2012, false, 60),
  ('halloween', 'kids', 'Corpse Bride', 2005, false, 70),
  ('halloween', 'kids', 'Hotel Transylvania', 2012, false, 80),
  ('halloween', 'kids', 'Hotel Transylvania 2', 2015, false, 90),
  ('halloween', 'kids', 'Hotel Transylvania 3: Summer Vacation', 2018, false, 100),
  ('halloween', 'kids', 'Hotel Transylvania: Transformania', 2022, false, 110),
  ('halloween', 'kids', 'Casper', 1995, false, 120),
  ('halloween', 'kids', 'The Addams Family', 1991, false, 130),
  ('halloween', 'kids', 'Addams Family Values', 1993, false, 140),
  ('halloween', 'kids', 'The Addams Family', 2019, false, 150),
  ('halloween', 'kids', 'The Addams Family 2', 2021, false, 160),
  ('halloween', 'kids', 'Halloweentown', 1998, false, 170),
  ('halloween', 'kids', 'Halloweentown II: Kalabar''s Revenge', 2001, false, 180),
  ('halloween', 'kids', 'Halloweentown High', 2004, false, 190),
  ('halloween', 'kids', 'Return to Halloweentown', 2006, false, 200),
  ('halloween', 'kids', 'Twitches', 2005, false, 210),
  ('halloween', 'kids', 'Twitches Too', 2007, false, 220),
  ('halloween', 'kids', 'Goosebumps', 2015, false, 230),
  ('halloween', 'kids', 'Goosebumps 2: Haunted Halloween', 2018, false, 240),
  ('halloween', 'kids', 'Monsters, Inc.', 2001, false, 250),
  ('halloween', 'kids', 'Monsters University', 2013, false, 260),
  ('halloween', 'kids', 'Scooby-Doo', 2002, false, 270),
  ('halloween', 'kids', 'Scooby-Doo 2: Monsters Unleashed', 2004, false, 280),
  ('halloween', 'kids', 'Scoob!', 2020, false, 290),
  ('halloween', 'kids', 'The Witches', 1990, false, 300),
  ('halloween', 'kids', 'The Witches', 2020, false, 310),
  ('halloween', 'kids', 'Beetlejuice', 1988, false, 320),
  ('halloween', 'kids', 'Beetlejuice Beetlejuice', 2024, false, 330),
  ('halloween', 'kids', 'Ghostbusters', 1984, false, 340),
  ('halloween', 'kids', 'Ghostbusters II', 1989, false, 350),
  ('halloween', 'kids', 'Ghostbusters: Afterlife', 2021, false, 360),
  ('halloween', 'kids', 'Ghostbusters: Frozen Empire', 2024, false, 370),
  ('halloween', 'kids', 'The Haunted Mansion', 2003, false, 380),
  ('halloween', 'kids', 'Haunted Mansion', 2023, false, 390),
  ('halloween', 'kids', 'Ernest Scared Stupid', 1991, false, 400),
  ('halloween', 'kids', 'The Little Vampire', 2000, false, 410),
  ('halloween', 'kids', 'Igor', 2008, false, 420),
  ('halloween', 'kids', 'Wendell & Wild', 2022, false, 430),
  ('halloween', 'kids', 'Room on the Broom', 2012, false, 440),
  ('halloween', 'kids', 'Spookley the Square Pumpkin', 2004, false, 450),
  ('halloween', 'kids', 'Under Wraps', 2021, false, 460),
  ('halloween', 'kids', 'The Monster Squad', 1987, false, 470),
  ('halloween', 'kids', 'Gremlins', 1984, false, 480),
  ('halloween', 'kids', 'Casper Meets Wendy', 1998, false, 490),
  ('halloween', 'kids', 'Mr. Boogedy', 1986, false, 500),
  ('halloween', 'kids', 'Leroy & Stitch', 2006, false, 510),
  ('halloween', 'kids', 'It''s the Great Pumpkin, Charlie Brown', 1966, false, 520),
  ('halloween', 'kids', 'The Worst Witch', 1986, false, 530),
  ('halloween', 'kids', 'Scary Godmother: Halloween Spooktakular', 2003, false, 540),
  ('halloween', 'kids', 'Fun Size', 2012, false, 550),
  ('halloween', 'kids', 'Hubie Halloween', 2020, false, 560),
  ('halloween', 'kids', 'Nanny McPhee', 2005, false, 570),
  ('halloween', 'kids', 'Matilda', 1996, false, 580),
  ('halloween', 'kidshows', 'Scooby-Doo, Where Are You!', 1969, true, 0),
  ('halloween', 'kidshows', 'Goosebumps', 1995, true, 10),
  ('halloween', 'kidshows', 'Goosebumps', 2023, true, 20),
  ('halloween', 'kidshows', 'Are You Afraid of the Dark?', 1990, true, 30),
  ('halloween', 'kidshows', 'Over the Garden Wall', 2014, true, 40),
  ('halloween', 'kidshows', 'The Addams Family', 1964, true, 50),
  ('halloween', 'kidshows', 'The Munsters', 1964, true, 60),
  ('halloween', 'kidshows', 'Wednesday', 2022, true, 70),
  ('halloween', 'kidshows', 'Gravity Falls', 2012, true, 80),
  ('halloween', 'kidshows', 'Courage the Cowardly Dog', 1999, true, 90),
  ('halloween', 'kidshows', 'The Real Ghostbusters', 1986, true, 100),
  ('halloween', 'kidshows', 'Ghosts', 2021, true, 110),
  ('halloween', 'kidshows', 'Sabrina the Teenage Witch', 1996, true, 120),
  ('halloween', 'kidshows', 'Hotel Transylvania: The Series', 2017, true, 130),
  ('halloween', 'night', 'Halloween', 1978, false, 0),
  ('halloween', 'night', 'Halloween II', 1981, false, 10),
  ('halloween', 'night', 'Halloween III: Season of the Witch', 1982, false, 20),
  ('halloween', 'night', 'Halloween 4: The Return of Michael Myers', 1988, false, 30),
  ('halloween', 'night', 'Halloween H20: 20 Years Later', 1998, false, 40),
  ('halloween', 'night', 'Halloween', 2007, false, 50),
  ('halloween', 'night', 'Halloween', 2018, false, 60),
  ('halloween', 'night', 'Halloween Kills', 2021, false, 70),
  ('halloween', 'night', 'Halloween Ends', 2022, false, 80),
  ('halloween', 'night', 'Trick ''r Treat', 2007, false, 90),
  ('halloween', 'night', 'Tales of Halloween', 2015, false, 100),
  ('halloween', 'night', 'Night of the Demons', 1988, false, 110),
  ('halloween', 'night', 'Terrifier', 2016, false, 120),
  ('halloween', 'night', 'Terrifier 2', 2022, false, 130),
  ('halloween', 'night', 'Terrifier 3', 2024, false, 140),
  ('halloween', 'night', 'Hell Fest', 2018, false, 150),
  ('halloween', 'night', 'The Houses October Built', 2014, false, 160),
  ('halloween', 'night', 'All Hallows'' Eve', 2013, false, 170),
  ('halloween', 'night', 'Satan''s Little Helper', 2004, false, 180),
  ('halloween', 'night', 'Totally Killer', 2023, false, 190),
  ('halloween', 'classics', 'Psycho', 1960, false, 0),
  ('halloween', 'classics', 'Night of the Living Dead', 1968, false, 10),
  ('halloween', 'classics', 'Rosemary''s Baby', 1968, false, 20),
  ('halloween', 'classics', 'The Exorcist', 1973, false, 30),
  ('halloween', 'classics', 'The Wicker Man', 1973, false, 40),
  ('halloween', 'classics', 'The Texas Chain Saw Massacre', 1974, false, 50),
  ('halloween', 'classics', 'Black Christmas', 1974, false, 60),
  ('halloween', 'classics', 'Jaws', 1975, false, 70),
  ('halloween', 'classics', 'Carrie', 1976, false, 80),
  ('halloween', 'classics', 'The Omen', 1976, false, 90),
  ('halloween', 'classics', 'Suspiria', 1977, false, 100),
  ('halloween', 'classics', 'The Hills Have Eyes', 1977, false, 110),
  ('halloween', 'classics', 'Halloween', 1978, false, 120),
  ('halloween', 'classics', 'Dawn of the Dead', 1978, false, 130),
  ('halloween', 'classics', 'Invasion of the Body Snatchers', 1978, false, 140),
  ('halloween', 'classics', 'Alien', 1979, false, 150),
  ('halloween', 'classics', 'Phantasm', 1979, false, 160),
  ('halloween', 'classics', 'The Amityville Horror', 1979, false, 170),
  ('halloween', 'classics', 'The Shining', 1980, false, 180),
  ('halloween', 'classics', 'The Fog', 1980, false, 190),
  ('halloween', 'classics', 'The Changeling', 1980, false, 200),
  ('halloween', 'classics', 'Friday the 13th', 1980, false, 210),
  ('halloween', 'classics', 'An American Werewolf in London', 1981, false, 220),
  ('halloween', 'classics', 'The Evil Dead', 1981, false, 230),
  ('halloween', 'classics', 'The Thing', 1982, false, 240),
  ('halloween', 'classics', 'Poltergeist', 1982, false, 250),
  ('halloween', 'classics', 'Christine', 1983, false, 260),
  ('halloween', 'classics', 'Cujo', 1983, false, 270),
  ('halloween', 'classics', 'A Nightmare on Elm Street', 1984, false, 280),
  ('halloween', 'classics', 'The Fly', 1986, false, 290),
  ('halloween', 'classics', 'Hellraiser', 1987, false, 300),
  ('halloween', 'classics', 'Pet Sematary', 1989, false, 310),
  ('halloween', 'classics', 'Nosferatu', 1922, false, 320),
  ('halloween', 'classics', 'Dracula', 1931, false, 330),
  ('halloween', 'classics', 'Frankenstein', 1931, false, 340),
  ('halloween', 'classics', 'Bride of Frankenstein', 1935, false, 350),
  ('halloween', 'classics', 'Creature from the Black Lagoon', 1954, false, 360),
  ('halloween', 'classics', 'House on Haunted Hill', 1959, false, 370),
  ('halloween', 'classics', 'The Innocents', 1961, false, 380),
  ('halloween', 'classics', 'The Birds', 1963, false, 390),
  ('halloween', 'classics', 'The Haunting', 1963, false, 400),
  ('halloween', 'occult', 'The Exorcist', 1973, false, 0),
  ('halloween', 'occult', 'The Exorcist III', 1990, false, 10),
  ('halloween', 'occult', 'Rosemary''s Baby', 1968, false, 20),
  ('halloween', 'occult', 'The Omen', 1976, false, 30),
  ('halloween', 'occult', 'Hereditary', 2018, false, 40),
  ('halloween', 'occult', 'The Conjuring', 2013, false, 50),
  ('halloween', 'occult', 'The Conjuring 2', 2016, false, 60),
  ('halloween', 'occult', 'The Conjuring: The Devil Made Me Do It', 2021, false, 70),
  ('halloween', 'occult', 'Annabelle', 2014, false, 80),
  ('halloween', 'occult', 'Annabelle: Creation', 2017, false, 90),
  ('halloween', 'occult', 'The Nun', 2018, false, 100),
  ('halloween', 'occult', 'Sinister', 2012, false, 110),
  ('halloween', 'occult', 'The Witch', 2015, false, 120),
  ('halloween', 'occult', 'Midsommar', 2019, false, 130),
  ('halloween', 'occult', 'The Wicker Man', 1973, false, 140),
  ('halloween', 'occult', 'Drag Me to Hell', 2009, false, 150),
  ('halloween', 'occult', 'The Evil Dead', 1981, false, 160),
  ('halloween', 'occult', 'Evil Dead II', 1987, false, 170),
  ('halloween', 'occult', 'Evil Dead', 2013, false, 180),
  ('halloween', 'occult', 'Evil Dead Rise', 2023, false, 190),
  ('halloween', 'occult', 'Talk to Me', 2022, false, 200),
  ('halloween', 'occult', 'The Exorcism of Emily Rose', 2005, false, 210),
  ('halloween', 'occult', 'The Rite', 2011, false, 220),
  ('halloween', 'occult', 'The Last Exorcism', 2010, false, 230),
  ('halloween', 'occult', 'Late Night with the Devil', 2023, false, 240),
  ('halloween', 'occult', 'Longlegs', 2024, false, 250),
  ('halloween', 'occult', 'Smile', 2022, false, 260),
  ('halloween', 'occult', 'Smile 2', 2024, false, 270),
  ('halloween', 'occult', 'Suspiria', 1977, false, 280),
  ('halloween', 'occult', 'Suspiria', 2018, false, 290),
  ('halloween', 'occult', 'The Craft', 1996, false, 300),
  ('halloween', 'occult', 'Hellraiser', 1987, false, 310),
  ('halloween', 'occult', 'The Blackcoat''s Daughter', 2015, false, 320),
  ('halloween', 'occult', 'The Pope''s Exorcist', 2023, false, 330),
  ('halloween', 'occult', 'Deliver Us from Evil', 2014, false, 340),
  ('halloween', 'occult', 'The Autopsy of Jane Doe', 2016, false, 350),
  ('halloween', 'occult', 'Kill List', 2011, false, 360),
  ('halloween', 'occult', 'The Ninth Gate', 1999, false, 370),
  ('halloween', 'occult', 'Constantine', 2005, false, 380),
  ('halloween', 'witches', 'The Witch', 2015, false, 0),
  ('halloween', 'witches', 'The Craft', 1996, false, 10),
  ('halloween', 'witches', 'The Craft: Legacy', 2020, false, 20),
  ('halloween', 'witches', 'Suspiria', 1977, false, 30),
  ('halloween', 'witches', 'Suspiria', 2018, false, 40),
  ('halloween', 'witches', 'The Witches of Eastwick', 1987, false, 50),
  ('halloween', 'witches', 'Practical Magic', 1998, false, 60),
  ('halloween', 'witches', 'The Love Witch', 2016, false, 70),
  ('halloween', 'witches', 'The Last Witch Hunter', 2015, false, 80),
  ('halloween', 'witches', 'Season of the Witch', 2011, false, 90),
  ('halloween', 'witches', 'Hansel & Gretel: Witch Hunters', 2013, false, 100),
  ('halloween', 'witches', 'Pyewacket', 2017, false, 110),
  ('halloween', 'witches', 'The Wretched', 2019, false, 120),
  ('halloween', 'witches', 'Hagazussa', 2017, false, 130),
  ('halloween', 'witches', 'You Won''t Be Alone', 2022, false, 140),
  ('halloween', 'witches', 'Gretel & Hansel', 2020, false, 150),
  ('halloween', 'witches', 'Hereditary', 2018, false, 160),
  ('halloween', 'witches', 'Halloween III: Season of the Witch', 1982, false, 170),
  ('halloween', 'witches', 'The Blackcoat''s Daughter', 2015, false, 180),
  ('halloween', 'witches', 'Agatha All Along', 2024, true, 190),
  ('halloween', 'witches', 'Chilling Adventures of Sabrina', 2018, true, 200),
  ('halloween', 'witches', 'Mayfair Witches', 2023, true, 210),
  ('halloween', 'haunted', 'The Shining', 1980, false, 0),
  ('halloween', 'haunted', 'Poltergeist', 1982, false, 10),
  ('halloween', 'haunted', 'The Others', 2001, false, 20),
  ('halloween', 'haunted', 'The Amityville Horror', 1979, false, 30),
  ('halloween', 'haunted', 'The Amityville Horror', 2005, false, 40),
  ('halloween', 'haunted', 'The Haunting', 1963, false, 50),
  ('halloween', 'haunted', 'The Changeling', 1980, false, 60),
  ('halloween', 'haunted', 'The Orphanage', 2007, false, 70),
  ('halloween', 'haunted', 'Crimson Peak', 2015, false, 80),
  ('halloween', 'haunted', 'The Ring', 2002, false, 90),
  ('halloween', 'haunted', 'The Grudge', 2004, false, 100),
  ('halloween', 'haunted', 'Paranormal Activity', 2007, false, 110),
  ('halloween', 'haunted', 'Insidious', 2011, false, 120),
  ('halloween', 'haunted', 'Insidious: Chapter 2', 2013, false, 130),
  ('halloween', 'haunted', '1408', 2007, false, 140),
  ('halloween', 'haunted', 'The Woman in Black', 2012, false, 150),
  ('halloween', 'haunted', 'The Innocents', 1961, false, 160),
  ('halloween', 'haunted', 'House on Haunted Hill', 1959, false, 170),
  ('halloween', 'haunted', 'House on Haunted Hill', 1999, false, 180),
  ('halloween', 'haunted', 'Lights Out', 2016, false, 190),
  ('halloween', 'haunted', 'Oculus', 2014, false, 200),
  ('halloween', 'haunted', 'The Devil''s Backbone', 2001, false, 210),
  ('halloween', 'haunted', 'Mama', 2013, false, 220),
  ('halloween', 'haunted', 'The Babadook', 2014, false, 230),
  ('halloween', 'haunted', 'Dark Water', 2002, false, 240),
  ('halloween', 'haunted', 'Ghost Stories', 2018, false, 250),
  ('halloween', 'haunted', 'The Conjuring', 2013, false, 260),
  ('halloween', 'haunted', 'A Haunting in Venice', 2023, false, 270),
  ('halloween', 'haunted', 'The Sixth Sense', 1999, false, 280),
  ('halloween', 'haunted', 'Ringu', 1998, false, 290),
  ('halloween', 'slashers', 'Scream', 1996, false, 0),
  ('halloween', 'slashers', 'Scream 2', 1997, false, 10),
  ('halloween', 'slashers', 'Scream 3', 2000, false, 20),
  ('halloween', 'slashers', 'Scream 4', 2011, false, 30),
  ('halloween', 'slashers', 'Scream', 2022, false, 40),
  ('halloween', 'slashers', 'Scream VI', 2023, false, 50),
  ('halloween', 'slashers', 'Friday the 13th', 1980, false, 60),
  ('halloween', 'slashers', 'Friday the 13th', 2009, false, 70),
  ('halloween', 'slashers', 'A Nightmare on Elm Street', 1984, false, 80),
  ('halloween', 'slashers', 'A Nightmare on Elm Street', 2010, false, 90),
  ('halloween', 'slashers', 'The Texas Chain Saw Massacre', 1974, false, 100),
  ('halloween', 'slashers', 'The Texas Chainsaw Massacre', 2003, false, 110),
  ('halloween', 'slashers', 'Black Christmas', 1974, false, 120),
  ('halloween', 'slashers', 'Child''s Play', 1988, false, 130),
  ('halloween', 'slashers', 'Child''s Play', 2019, false, 140),
  ('halloween', 'slashers', 'Bride of Chucky', 1998, false, 150),
  ('halloween', 'slashers', 'I Know What You Did Last Summer', 1997, false, 160),
  ('halloween', 'slashers', 'Urban Legend', 1998, false, 170),
  ('halloween', 'slashers', 'Happy Death Day', 2017, false, 180),
  ('halloween', 'slashers', 'X', 2022, false, 190),
  ('halloween', 'slashers', 'Pearl', 2022, false, 200),
  ('halloween', 'slashers', 'MaXXXine', 2024, false, 210),
  ('halloween', 'slashers', 'Candyman', 1992, false, 220),
  ('halloween', 'slashers', 'Candyman', 2021, false, 230),
  ('halloween', 'slashers', 'The Strangers', 2008, false, 240),
  ('halloween', 'slashers', 'You''re Next', 2011, false, 250),
  ('halloween', 'slashers', 'Final Destination', 2000, false, 260),
  ('halloween', 'slashers', 'Final Destination: Bloodlines', 2025, false, 270),
  ('halloween', 'slashers', 'My Bloody Valentine', 1981, false, 280),
  ('halloween', 'slashers', 'Sleepaway Camp', 1983, false, 290),
  ('halloween', 'slashers', 'Fear Street: 1994', 2021, false, 300),
  ('halloween', 'slashers', 'Fear Street: 1978', 2021, false, 310),
  ('halloween', 'slashers', 'Fear Street: 1666', 2021, false, 320),
  ('halloween', 'slashers', 'Thanksgiving', 2023, false, 330),
  ('halloween', 'gore', 'Saw', 2004, false, 0),
  ('halloween', 'gore', 'Saw II', 2005, false, 10),
  ('halloween', 'gore', 'Saw III', 2006, false, 20),
  ('halloween', 'gore', 'Saw IV', 2007, false, 30),
  ('halloween', 'gore', 'Saw X', 2023, false, 40),
  ('halloween', 'gore', 'Hostel', 2005, false, 50),
  ('halloween', 'gore', 'Hostel: Part II', 2007, false, 60),
  ('halloween', 'gore', 'Terrifier', 2016, false, 70),
  ('halloween', 'gore', 'Terrifier 2', 2022, false, 80),
  ('halloween', 'gore', 'Terrifier 3', 2024, false, 90),
  ('halloween', 'gore', 'Evil Dead', 2013, false, 100),
  ('halloween', 'gore', 'Evil Dead Rise', 2023, false, 110),
  ('halloween', 'gore', 'The Texas Chainsaw Massacre', 2003, false, 120),
  ('halloween', 'gore', 'Wrong Turn', 2003, false, 130),
  ('halloween', 'gore', 'The Hills Have Eyes', 2006, false, 140),
  ('halloween', 'gore', 'House of 1000 Corpses', 2003, false, 150),
  ('halloween', 'gore', 'The Devil''s Rejects', 2005, false, 160),
  ('halloween', 'gore', 'Martyrs', 2008, false, 170),
  ('halloween', 'gore', 'High Tension', 2003, false, 180),
  ('halloween', 'gore', 'Inside', 2007, false, 190),
  ('halloween', 'gore', 'Hellraiser', 2022, false, 200),
  ('halloween', 'gore', 'Braindead', 1992, false, 210),
  ('halloween', 'gore', 'Dead Alive', 1992, false, 220),
  ('halloween', 'gore', 'Raw', 2016, false, 230),
  ('halloween', 'gore', 'The Collector', 2009, false, 240),
  ('halloween', 'gore', 'Mandy', 2018, false, 250),
  ('halloween', 'gore', 'The Green Inferno', 2013, false, 260),
  ('halloween', 'gore', 'Piranha 3D', 2010, false, 270),
  ('halloween', 'gore', 'Cabin Fever', 2002, false, 280),
  ('halloween', 'gore', 'Wolf Creek', 2005, false, 290),
  ('halloween', 'gore', 'The Sadness', 2021, false, 300),
  ('halloween', 'gore', 'In a Violent Nature', 2024, false, 310),
  ('halloween', 'gore', 'Final Destination 2', 2003, false, 320),
  ('halloween', 'gore', 'Final Destination 3', 2006, false, 330),
  ('halloween', 'gore', 'The Final Destination', 2009, false, 340),
  ('halloween', 'gore', 'Final Destination 5', 2011, false, 350),
  ('halloween', 'gore', 'Jeepers Creepers', 2001, false, 360),
  ('halloween', 'gore', 'Thanksgiving', 2023, false, 370),
  ('halloween', 'monsters', 'Dracula', 1931, false, 0),
  ('halloween', 'monsters', 'Bram Stoker''s Dracula', 1992, false, 10),
  ('halloween', 'monsters', 'Nosferatu', 1922, false, 20),
  ('halloween', 'monsters', 'Nosferatu', 2024, false, 30),
  ('halloween', 'monsters', 'Interview with the Vampire', 1994, false, 40),
  ('halloween', 'monsters', 'The Lost Boys', 1987, false, 50),
  ('halloween', 'monsters', 'Fright Night', 1985, false, 60),
  ('halloween', 'monsters', 'Fright Night', 2011, false, 70),
  ('halloween', 'monsters', '30 Days of Night', 2007, false, 80),
  ('halloween', 'monsters', 'Let the Right One In', 2008, false, 90),
  ('halloween', 'monsters', 'Near Dark', 1987, false, 100),
  ('halloween', 'monsters', 'From Dusk Till Dawn', 1996, false, 110),
  ('halloween', 'monsters', 'Blade', 1998, false, 120),
  ('halloween', 'monsters', 'An American Werewolf in London', 1981, false, 130),
  ('halloween', 'monsters', 'The Howling', 1981, false, 140),
  ('halloween', 'monsters', 'Ginger Snaps', 2000, false, 150),
  ('halloween', 'monsters', 'Dog Soldiers', 2002, false, 160),
  ('halloween', 'monsters', 'The Wolf Man', 1941, false, 170),
  ('halloween', 'monsters', 'The Wolfman', 2010, false, 180),
  ('halloween', 'monsters', 'Frankenstein', 1931, false, 190),
  ('halloween', 'monsters', 'Bride of Frankenstein', 1935, false, 200),
  ('halloween', 'monsters', 'The Mummy', 1932, false, 210),
  ('halloween', 'monsters', 'The Mummy', 1999, false, 220),
  ('halloween', 'monsters', 'Creature from the Black Lagoon', 1954, false, 230),
  ('halloween', 'monsters', 'The Invisible Man', 1933, false, 240),
  ('halloween', 'monsters', 'The Invisible Man', 2020, false, 250),
  ('halloween', 'monsters', 'The Thing', 1982, false, 260),
  ('halloween', 'monsters', 'Alien', 1979, false, 270),
  ('halloween', 'monsters', 'Tremors', 1990, false, 280),
  ('halloween', 'monsters', 'It', 2017, false, 290),
  ('halloween', 'monsters', 'It Chapter Two', 2019, false, 300),
  ('halloween', 'monsters', 'The Fly', 1986, false, 310),
  ('halloween', 'monsters', 'Van Helsing', 2004, false, 320),
  ('halloween', 'monsters', 'Underworld', 2003, false, 330),
  ('halloween', 'monsters', 'Renfield', 2023, false, 340),
  ('halloween', 'monsters', 'Abigail', 2024, false, 350),
  ('halloween', 'monsters', 'Sinners', 2025, false, 360),
  ('halloween', 'zombies', 'Night of the Living Dead', 1968, false, 0),
  ('halloween', 'zombies', 'Dawn of the Dead', 1978, false, 10),
  ('halloween', 'zombies', 'Dawn of the Dead', 2004, false, 20),
  ('halloween', 'zombies', 'Day of the Dead', 1985, false, 30),
  ('halloween', 'zombies', '28 Days Later', 2002, false, 40),
  ('halloween', 'zombies', '28 Weeks Later', 2007, false, 50),
  ('halloween', 'zombies', '28 Years Later', 2025, false, 60),
  ('halloween', 'zombies', 'Train to Busan', 2016, false, 70),
  ('halloween', 'zombies', 'World War Z', 2013, false, 80),
  ('halloween', 'zombies', 'The Return of the Living Dead', 1985, false, 90),
  ('halloween', 'zombies', '[REC]', 2007, false, 100),
  ('halloween', 'zombies', 'Army of the Dead', 2021, false, 110),
  ('halloween', 'zombies', 'Resident Evil', 2002, false, 120),
  ('halloween', 'zombies', 'I Am Legend', 2007, false, 130),
  ('halloween', 'zombies', 'The Girl with All the Gifts', 2016, false, 140),
  ('halloween', 'zombies', 'Zombieland', 2009, false, 150),
  ('halloween', 'zombies', 'Zombieland: Double Tap', 2019, false, 160),
  ('halloween', 'zombies', 'Warm Bodies', 2013, false, 170),
  ('halloween', 'comedy', 'Shaun of the Dead', 2004, false, 0),
  ('halloween', 'comedy', 'Tucker and Dale vs. Evil', 2010, false, 10),
  ('halloween', 'comedy', 'The Cabin in the Woods', 2012, false, 20),
  ('halloween', 'comedy', 'Ready or Not', 2019, false, 30),
  ('halloween', 'comedy', 'What We Do in the Shadows', 2014, false, 40),
  ('halloween', 'comedy', 'Scary Movie', 2000, false, 50),
  ('halloween', 'comedy', 'Young Frankenstein', 1974, false, 60),
  ('halloween', 'comedy', 'Death Becomes Her', 1992, false, 70),
  ('halloween', 'comedy', 'Little Shop of Horrors', 1986, false, 80),
  ('halloween', 'comedy', 'The Rocky Horror Picture Show', 1975, false, 90),
  ('halloween', 'comedy', 'Army of Darkness', 1992, false, 100),
  ('halloween', 'comedy', 'Freaky', 2020, false, 110),
  ('halloween', 'comedy', 'Idle Hands', 1999, false, 120),
  ('halloween', 'comedy', 'The Frighteners', 1996, false, 130),
  ('halloween', 'comedy', 'Slither', 2006, false, 140),
  ('halloween', 'comedy', 'Krampus', 2015, false, 150),
  ('halloween', 'comedy', 'Werewolves Within', 2021, false, 160),
  ('halloween', 'comedy', 'The Babysitter', 2017, false, 170),
  ('halloween', 'comedy', 'Jennifer''s Body', 2009, false, 180),
  ('halloween', 'comedy', 'Zombieland', 2009, false, 190),
  ('halloween', 'comedy', 'Arachnophobia', 1990, false, 200),
  ('halloween', 'comedy', 'Lisa Frankenstein', 2024, false, 210),
  ('halloween', 'found', 'The Blair Witch Project', 1999, false, 0),
  ('halloween', 'found', 'Blair Witch', 2016, false, 10),
  ('halloween', 'found', 'Paranormal Activity', 2007, false, 20),
  ('halloween', 'found', 'Paranormal Activity 2', 2010, false, 30),
  ('halloween', 'found', 'Paranormal Activity 3', 2011, false, 40),
  ('halloween', 'found', '[REC]', 2007, false, 50),
  ('halloween', 'found', 'Quarantine', 2008, false, 60),
  ('halloween', 'found', 'Cloverfield', 2008, false, 70),
  ('halloween', 'found', 'V/H/S', 2012, false, 80),
  ('halloween', 'found', 'V/H/S/2', 2013, false, 90),
  ('halloween', 'found', 'Grave Encounters', 2011, false, 100),
  ('halloween', 'found', 'Creep', 2014, false, 110),
  ('halloween', 'found', 'Creep 2', 2017, false, 120),
  ('halloween', 'found', 'The Taking of Deborah Logan', 2014, false, 130),
  ('halloween', 'found', 'Hell House LLC', 2015, false, 140),
  ('halloween', 'found', 'Host', 2020, false, 150),
  ('halloween', 'found', 'Lake Mungo', 2008, false, 160),
  ('halloween', 'found', 'The Visit', 2015, false, 170),
  ('halloween', 'found', 'Unfriended', 2014, false, 180),
  ('halloween', 'found', 'As Above, So Below', 2014, false, 190),
  ('halloween', 'found', 'The Last Exorcism', 2010, false, 200),
  ('halloween', 'found', 'Deadstream', 2022, false, 210),
  ('halloween', 'found', 'Late Night with the Devil', 2023, false, 220),
  ('halloween', 'psych', 'Get Out', 2017, false, 0),
  ('halloween', 'psych', 'Us', 2019, false, 10),
  ('halloween', 'psych', 'Nope', 2022, false, 20),
  ('halloween', 'psych', 'The Silence of the Lambs', 1991, false, 30),
  ('halloween', 'psych', 'Psycho', 1960, false, 40),
  ('halloween', 'psych', 'It Follows', 2014, false, 50),
  ('halloween', 'psych', 'A Quiet Place', 2018, false, 60),
  ('halloween', 'psych', 'A Quiet Place Part II', 2020, false, 70),
  ('halloween', 'psych', 'Barbarian', 2022, false, 80),
  ('halloween', 'psych', 'The Descent', 2005, false, 90),
  ('halloween', 'psych', 'Saw', 2004, false, 100),
  ('halloween', 'psych', 'The Blair Witch Project', 1999, false, 110),
  ('halloween', 'psych', 'Jaws', 1975, false, 120),
  ('halloween', 'psych', 'The Birds', 1963, false, 130),
  ('halloween', 'psych', 'Carrie', 1976, false, 140),
  ('halloween', 'psych', 'Misery', 1990, false, 150),
  ('halloween', 'psych', 'The Lighthouse', 2019, false, 160),
  ('halloween', 'psych', 'Speak No Evil', 2024, false, 170),
  ('halloween', 'psych', 'Weapons', 2025, false, 180),
  ('halloween', 'psych', 'The Substance', 2024, false, 190),
  ('halloween', 'psych', 'Bird Box', 2018, false, 200),
  ('halloween', 'psych', 'The Visit', 2015, false, 210),
  ('halloween', 'psych', 'Split', 2016, false, 220),
  ('halloween', 'psych', 'Green Room', 2015, false, 230),
  ('halloween', 'psych', 'Don''t Breathe', 2016, false, 240),
  ('halloween', 'psych', 'Rosemary''s Baby', 1968, false, 250),
  ('halloween', 'psych', 'The Menu', 2022, false, 260),
  ('halloween', 'new', 'Weapons', 2025, false, 0),
  ('halloween', 'new', 'Sinners', 2025, false, 10),
  ('halloween', 'new', '28 Years Later', 2025, false, 20),
  ('halloween', 'new', 'Final Destination: Bloodlines', 2025, false, 30),
  ('halloween', 'new', 'Companion', 2025, false, 40),
  ('halloween', 'new', 'Bring Her Back', 2025, false, 50),
  ('halloween', 'new', 'The Monkey', 2025, false, 60),
  ('halloween', 'new', 'Until Dawn', 2025, false, 70),
  ('halloween', 'new', 'Together', 2025, false, 80),
  ('halloween', 'new', 'Black Phone 2', 2025, false, 90),
  ('halloween', 'new', 'Five Nights at Freddy''s 2', 2025, false, 100),
  ('halloween', 'new', 'Frankenstein', 2025, false, 110),
  ('halloween', 'new', 'Wolf Man', 2025, false, 120),
  ('halloween', 'new', 'M3GAN 2.0', 2025, false, 130),
  ('halloween', 'new', 'Nosferatu', 2024, false, 140),
  ('halloween', 'new', 'Longlegs', 2024, false, 150),
  ('halloween', 'new', 'Abigail', 2024, false, 160),
  ('halloween', 'new', 'The Substance', 2024, false, 170),
  ('halloween', 'new', 'Heretic', 2024, false, 180),
  ('halloween', 'new', 'Speak No Evil', 2024, false, 190),
  ('halloween', 'new', 'Terrifier 3', 2024, false, 200),
  ('halloween', 'new', 'Alien: Romulus', 2024, false, 210),
  ('halloween', 'new', 'Smile 2', 2024, false, 220),
  ('halloween', 'new', 'MaXXXine', 2024, false, 230),
  ('halloween', 'new', 'Late Night with the Devil', 2023, false, 240),
  ('halloween', 'new', 'Talk to Me', 2022, false, 250),
  ('halloween', 'new', 'Evil Dead Rise', 2023, false, 260),
  ('halloween', 'new', 'Five Nights at Freddy''s', 2023, false, 270),
  ('halloween', 'new', 'Scream VI', 2023, false, 280),
  ('halloween', 'new', 'Totally Killer', 2023, false, 290),
  ('halloween', 'new', 'Smile', 2022, false, 300),
  ('halloween', 'new', 'Barbarian', 2022, false, 310),
  ('halloween', 'new', 'X', 2022, false, 320),
  ('halloween', 'new', 'Pearl', 2022, false, 330),
  ('halloween', 'new', 'M3GAN', 2022, false, 340),
  ('halloween', 'new', 'Nope', 2022, false, 350),
  ('halloween', 'new', 'The Black Phone', 2021, false, 360),
  ('halloween', 'series', 'Stranger Things', 2016, true, 0),
  ('halloween', 'series', 'The Haunting of Hill House', 2018, true, 10),
  ('halloween', 'series', 'The Haunting of Bly Manor', 2020, true, 20),
  ('halloween', 'series', 'Midnight Mass', 2021, true, 30),
  ('halloween', 'series', 'The Fall of the House of Usher', 2023, true, 40),
  ('halloween', 'series', 'The Walking Dead', 2010, true, 50),
  ('halloween', 'series', 'American Horror Story', 2011, true, 60),
  ('halloween', 'series', 'Supernatural', 2005, true, 70),
  ('halloween', 'series', 'Buffy the Vampire Slayer', 1997, true, 80),
  ('halloween', 'series', 'What We Do in the Shadows', 2019, true, 90),
  ('halloween', 'series', 'Chilling Adventures of Sabrina', 2018, true, 100),
  ('halloween', 'series', 'Evil', 2019, true, 110),
  ('halloween', 'series', 'Castlevania', 2017, true, 120),
  ('halloween', 'series', 'Interview with the Vampire', 2022, true, 130),
  ('halloween', 'series', 'Chucky', 2021, true, 140),
  ('halloween', 'series', 'Ash vs Evil Dead', 2015, true, 150),
  ('halloween', 'series', 'The Last of Us', 2023, true, 160),
  ('halloween', 'series', 'From', 2022, true, 170),
  ('halloween', 'series', 'Yellowjackets', 2021, true, 180),
  ('halloween', 'series', 'Penny Dreadful', 2014, true, 190),
  ('halloween', 'series', 'The X-Files', 1993, true, 200),
  ('halloween', 'series', 'Tales from the Crypt', 1989, true, 210)
) as v(season, row_id, title, year, is_show, sort)
where not exists (select 1 from public.seasonal_titles where season = 'halloween');