// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://falmwzhvxoefvkfsiylp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhbG13emh2eG9lZnZrZnNpeWxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MjIwNDMsImV4cCI6MjA2NzM5ODA0M30.I-YfvZxAuOvhehrdoZOgrANirZv0-ucGUKbW9gOfQak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// CRITICAL: For Android/FireTV, we use standard localStorage storage.
// The auth persistence is handled by:
// 1. src/utils/storage.ts - restores tokens from Capacitor Preferences to localStorage on startup
// 2. src/hooks/useAuth.ts - waits for storage restoration before checking session
// This ensures tokens survive app restarts even when Android WebView clears localStorage.

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    // Use default localStorage - our storage.ts restores it from Preferences on native startup
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
  }
});
